module.exports = {
  botName:    "ZIM XMD ULTIMATE",
  prefix:     ".",
  owner:      process.env.OWNER_NUMBER || "263780026088",
  ownerName:  "Malvin C",
  madeBy:     "Malvin C",
  country:    "Zimbabwe 🇿🇼",
  sessionId:  process.env.SESSION_ID || "",
  waChannel:  "https://whatsapp.com/channel/0029Vb7Eyki7T8bSNsTtjv1q",
  website:    "https://zim-xmd.onrender.com",
  github:     "https://github.com/malvin2010/zim-xmd",
  version:    "1.0.0",
  port:       process.env.PORT || 3000,
  autoRead:   true,
  autoTyping: true,
  welcomeMsg: true,
  antiLink:   false,
  antiSpam:   false,
};
